name: Run TicTacToe
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: g++ -std=c++17 -O2 -o tictactoe src/main.cpp
      - name: Run Game
        run: ./tictactoe
